services:
    _defaults:
        public: false

    Oro\Bundle\DotmailerBundle\Command\ContactsExportStatusUpdateCommand:
        arguments:
            - '@translator'
            - '@oro_message_queue.job.processor'
            - '@doctrine'
            - '@oro_message_queue.message_producer'
        tags:
            - { name: console.command }

    Oro\Bundle\DotmailerBundle\Command\FieldsForceSyncCommand:
        arguments:
            - '@doctrine'
            - '@oro_dotmailer.manager.sync_manager'
        tags:
            - { name: console.command }

    Oro\Bundle\DotmailerBundle\Command\ProcessMappedFieldsUpdatesCommand:
        arguments:
            - '@doctrine'
            - '@oro_dotmailer.processor.mapped_fields_change'
        tags:
            - { name: console.command }
