services:
    _defaults:
        public: false

    Oro\Bundle\DotmailerBundle\Command\ContactsExportStatusUpdateCommand:
        tags:
            - { name: console.command }

    Oro\Bundle\DotmailerBundle\Command\FieldsForceSyncCommand:
        arguments:
            - '@oro_dotmailer.manager.sync_manager'
            - '@doctrine'
        tags:
            - { name: console.command }

    Oro\Bundle\DotmailerBundle\Command\ProcessMappedFieldsUpdatesCommand:
        tags:
            - { name: console.command }
