services:
    _defaults:
        public: true

    Oro\Bundle\DotmailerBundle\Controller\DataFieldMappingController:
        calls:
            - [setContainer, ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }

    Oro\Bundle\DotmailerBundle\Controller\DotmailerController:
        calls:
            - [setContainer, ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
