system_configuration:
    groups:
        dotmailer_settings:
            title: oro.dotmailer.configuration.dotmailer_settings
            icon:  fa-envelope-o

        synchronization_dotmailer_settings:
            title: oro.dotmailer.configuration.dotmailer_synchronization

    fields:
        oro_dotmailer.datafields_sync_interval:
            data_type: string
            type: Symfony\Component\Form\Extension\Core\Type\TextType
            search_type: text
            priority: 10
            options:
                label:          oro.dotmailer.configuration.datafields_sync_interval
                tooltip:        oro.dotmailer.configuration.datafields_sync_interval.tooltip
                required: false

        oro_dotmailer.force_sync_for_virtual_fields:
            data_type: string
            type: Symfony\Component\Form\Extension\Core\Type\ChoiceType
            search_type: choice
            priority: 20
            options:
                label: oro.dotmailer.configuration.force_sync_for_virtual_fields.label
                tooltip: oro.dotmailer.configuration.force_sync_for_virtual_fields.tooltip
                required: true
                constraints:
                    - NotBlank: ~
                choices:
                    oro.dotmailer.configuration.force_sync_for_virtual_fields.choices.none: None
                    oro.dotmailer.configuration.force_sync_for_virtual_fields.choices.virtual_only: VirtualOnly
                    oro.dotmailer.configuration.force_sync_for_virtual_fields.choices.always: Always

    tree:
        system_configuration:
            platform:
                children:
                    integrations:
                        children:
                            dotmailer_settings:
                                priority: -20
                                children:
                                    synchronization_dotmailer_settings:
                                        priority: 10
                                        children:
                                            - oro_dotmailer.datafields_sync_interval
                                            - oro_dotmailer.force_sync_for_virtual_fields
